spring:
  datasource:
    url: jdbc:oracle:thin:@10.90.1.105:1521/DEV
    username: HR
    password: HR
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update